
const data = [
    {
      id:1,
      title: "UI/UX Design",
      link: "UI/UX Design",
      desc: "Unlock a world of knowledge through beautifully curated UI/UX design courses",
      img:"./software.png",
      className: "absolute mt-[-8px] top-[-90%]  right-[-19%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:2,
      title: "Software Development",
      link: "Software Development",
      desc: "Master the art of coding with transformative software development programs",
      img:"./img2.png",
      className: "absolute mt-[-8px] top-[-95%] right-[-15%] max-[1580px]:top-[-55%] max-[1451px]:top-[-95%] max-[1138px]:top-[-55%] max-[971px]:top-[-95%] max-[839px]:top-[-35%]",
  header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:3,
      title: "Mobile Development",
      link: "Mobile Development",
      desc: "Craft exceptional mobile experiences with cutting-edge development programs and resources.",
      img:"./img3.png",
      className: "absolute mt-[-8px] top-[-60%] right-[-5%] max-[1075px]:top-[-35%] ",
  header: "font-[600] text-[22px] text-white w-[80%]",
      
    },
    {
      id:4,
      title: "DevOps and Cloud Computing",
      link: "DevOps and Cloud Computing",
      desc: "Cultivate digital innovation through seamless DevOps and Cloud Computing integration",
      img:"./img4.png",
      className: "absolute mt-[-8px] top-[-50%]  right-[-18%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:5,
      title: "Desktop Development",
      link: "Desktop Development",
      desc: "Empower productivity with immersive experiences through desktop development mastery",
      img:"./img5.png",
      className:"absolute mt-[-8px] top-[-90%] right-[-5%] max-[1580px]:top-[-55%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:6,
      title: "Project Management",
      link: "Project Management",
      desc: "Drive success through effective planning and execution with expert project management.",
      img:"./img6.png",
      className:"absolute mt-[-8px] top-[-75%] right-[-5%] max-[1451px]:top-[-45%] ",
  header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:7,
      title: "HR and Talent",
      link: "HR and Talent",
      desc: "Unlock the potential of your workforce with strategic HR and talent management",
      img:"./img7.png",
      className: "absolute mt-[-8px] top-[-75%] right-[-5%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:8,
      title: "Sales and Marketing",
      link: "Sales and Marketing",
      desc: "Maximize reach and drive growth through dynamic sales and marketing strategies.",
      img:"./img8.png",
      className: "absolute mt-[-8px] top-[-75%] right-[-5%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
    {
      id:9,
      title: "Machine Learning",
      link: "Machine Learning",
      desc: "Unleash the power of AI/ML for transformative insights and intelligent solutions",
      img:"./img9.png",
      className: "absolute mt-[-8px] top-[-95%] right-[-5%]",
      header: "font-[600] text-[22px] text-white w-[80%]",
    },
   
  ];
  export default data;